### ISSUE TITLE
安装有点问题

### ISSUE THREAD

**Issue by weizhenhuan** [DresIsBoring/nvim-config#1]
我按照教程一步步来，也安装了packer，执行nvim后出现这个界面，跑:PackerInstall这个命令也跑不了，请问是怎么回事呢

![image](https://user-images.githubusercontent.com/55399998/154812207-2a87f1de-5900-4ced-a29e-2f07e767c10b.png)

**Comment by p-z-l** [comment]
`lua/core/keymaps.lua` 第 `20` 行应该是不需要的，直接删掉就行
